### ISSUE TITLE
Create a transaction

### ISSUE THREAD

**Issue by andymckay-limited-access** [mozilla/payments-service#28]
When we start the flow of processing a payment in payments-service we should start a transaction and then update it as we go along.

Then when we get the web hook from Braintree in mozilla/solitude#412, we can close the transaction.

**Comment by andymckay-limited-access** [comment]
Be sure to pass through id_pay through to the transaction, so we can hook it up later.

**Comment by andymckay** [comment]
I'm actually wondering if we should do this now. Overloading transaction is something we did in Bango because we needed the information. All the information about the transaction is in the webhook coming from Braintree. So what's the point? Debugging - we won't do it async this time it should be easier to debug, we'll have kibana for logging... Record keeping - we'll have control over the whole flow, we'll be able to track it all.

The more I think I about the more I think we can: throw out a pile of code, keep our flow simpler and get as good, or better information.

As a result I think I shouldn't merge this and remove all Transaction code from payments-service. a? @kumar303
